ssunnykku/Education-Management-System

- .gitignore
- src/main/java/com/kosta/ems/course/CourseController.java
- src/main/java/com/kosta/ems/course/CourseDTO.java
- src/main/java/com/kosta/ems/course/CourseMapper.java
- src/main/java/com/kosta/ems/course/CourseService.java
- src/main/java/com/kosta/ems/course/CourseServiceImpl.java
- src/main/java/com/kosta/ems/manager/ManagerController.java
- src/main/java/com/kosta/ems/manager/ManagerDTO.java
- src/main/java/com/kosta/ems/manager/ManagerMapper.java
- src/main/java/com/kosta/ems/manager/ManagerService.java
- src/main/java/com/kosta/ems/manager/ManagerServiceImpl.java
- src/main/resources/mapper/CourseMapper.xml
- src/main/resources/mapper/ManagerMapper.xml
- src/test/java/com/kosta/ems/course/CourseMapperTest.java
- src/test/java/com/kosta/ems/course/CourseServiceTest.java
- src/test/java/com/kosta/ems/manager/ManagerMapperTest.java
- src/test/java/com/kosta/ems/manager/ManagerServiceTest.java
Course, Manager 기능의 Mapper&Service 계층 완성
> Course&manager mapper&service

- src/main/java/com/kosta/ems/course/CourseController.java
- src/main/java/com/kosta/ems/courses/CourseController.java
- src/main/java/com/kosta/ems/courses/CourseDTO.java
- src/main/java/com/kosta/ems/courses/CourseMapper.java
- src/main/java/com/kosta/ems/courses/CourseService.java
- src/main/java/com/kosta/ems/courses/CourseServiceImpl.java
- src/main/java/com/kosta/ems/manager/ManagerController.java
- src/main/resources/mapper/CourseMapper.xml
- src/test/java/com/kosta/ems/course/CourseMapperTest.java
- src/test/java/com/kosta/ems/course/CourseServiceTest.java
> Course Restcontroller 완료

- src/main/java/com/kosta/ems/EmpController.java
- src/main/java/com/kosta/ems/courses/CourseController.java
- src/main/java/com/kosta/ems/courses/CourseMapper.java
- src/main/java/com/kosta/ems/courses/CourseService.java
- src/main/java/com/kosta/ems/courses/CourseServiceImpl.java
- src/main/resources/mapper/CourseMapper.xml
- src/main/resources/templates/courses/courseBoard.html
- src/test/java/com/kosta/ems/course/CourseMapperTest.java
- src/test/java/com/kosta/ems/course/CourseServiceTest.java
> Course BE 완료

- src/main/java/com/kosta/ems/student/AddStudentBasicInfoDTO.java
- src/main/java/com/kosta/ems/student/AddStudentCourseSeqDTO.java
- src/main/java/com/kosta/ems/student/IsRegisteredStudentDTO.java
- src/main/java/com/kosta/ems/student/RegisteredStudentInfoDTO.java
- src/main/java/com/kosta/ems/student/StudentCourseInfoDTO.java
- src/main/java/com/kosta/ems/student/StudentMapper.java
- src/main/java/com/kosta/ems/student/StudentService.java
- src/main/java/com/kosta/ems/student/StudentServiceImpl.java
- src/main/java/com/kosta/ems/student/UpdateSelectedStudentInfoDTO.java
- src/main/resources/mapper/StudentMapper.xml
- src/test/java/com/kosta/ems/student/StudentMapperTest.java
- src/test/java/com/kosta/ems/student/StudentServiceTest.java
* 수강생 정보 수정 mapper, service 구현 및 테스트 완료
* 수정
* 조회 - 페이지네이션 직접 구현을 위해 데이터 개수 sql, mapper 작성
* 등록 - mapper, service 코드 오타 및 일부 내용 수정
> feat: 수강생관리_수강생정보_수강생 등록, 수정 mapper, service 구현 및 일부 코드 수정

- src/main/java/com/kosta/ems/EmpController.java
- src/main/java/com/kosta/ems/course/CourseController.java
- src/main/java/com/kosta/ems/course/CourseDTO.java
- src/main/java/com/kosta/ems/course/CourseMapper.java
- src/main/java/com/kosta/ems/course/CourseService.java
- src/main/java/com/kosta/ems/course/CourseServiceImpl.java
- src/main/java/com/kosta/ems/manager/ManagerController.java
- src/main/java/com/kosta/ems/manager/ManagerDTO.java
- src/main/java/com/kosta/ems/manager/ManagerMapper.java
- src/main/java/com/kosta/ems/manager/ManagerService.java
- src/main/java/com/kosta/ems/manager/ManagerServiceImpl.java
- src/main/resources/mapper/CourseMapper.xml
- src/main/resources/mapper/ManagerMapper.xml
- src/test/java/com/kosta/ems/course/CourseMapperTest.java
- src/test/java/com/kosta/ems/course/CourseServiceTest.java
- src/test/java/com/kosta/ems/manager/ManagerMapperTest.java
- src/test/java/com/kosta/ems/manager/ManagerServiceTest.java
managers -> managers
courses -> course
> Hotfix: 패키지명 변경

- src/main/java/com/kosta/ems/EmpController.java
- src/main/java/com/kosta/ems/notification/NoResultsFoundException.java
- src/main/java/com/kosta/ems/notification/NotificationController.java
- src/main/java/com/kosta/ems/notification/NotificationMapper.java
- src/main/java/com/kosta/ems/notification/NotificationService.java
- src/main/java/com/kosta/ems/notification/NotificationServiceImpl.java
- src/main/resources/mapper/NotificationMapper.xml
- src/main/resources/templates/notifications/addNotification.html
- src/main/resources/templates/notifications/notificationBoard.html
- src/test/java/com/kosta/ems/notification/NotificationMapperTest.java
- src/test/java/com/kosta/ems/notification/NotificationServiceTest.java
notification Service 단위Test, Controller, restController 진행중
> feat: notification Service, Controller (not finished..)

- src/main/java/com/kosta/ems/EmpController.java
- src/main/java/com/kosta/ems/course/CourseController.java
- src/main/java/com/kosta/ems/course/CourseMapper.java
- src/main/java/com/kosta/ems/course/CourseService.java
- src/main/java/com/kosta/ems/course/CourseServiceImpl.java
- src/main/resources/mapper/CourseMapper.xml
- src/main/resources/static/css/courses.css
- src/main/resources/templates/courses/courseBoard.html
> 과정관리 기능 완료.

- src/main/java/com/kosta/ems/EmpController.java
> hotfix: course 패키지명 오타 수정

- src/main/java/com/kosta/ems/attendance/AttendanceController.java
- src/main/java/com/kosta/ems/attendance/AttendanceMapper.java
- src/main/java/com/kosta/ems/attendance/AttendanceService.java
- src/main/java/com/kosta/ems/attendance/AttendanceServiceImpl.java
- src/main/java/com/kosta/ems/attendance/RequestStudentAttendanceDTO.java
- src/main/java/com/kosta/ems/student/GetStudentInfoByScqDTO.java
- src/main/java/com/kosta/ems/student/StudentMapper.java
- src/main/resources/mapper/StudentMapper.xml
- src/test/java/com/kosta/ems/attendance/AttendanceServiceImplTest.java
- src/test/java/com/kosta/ems/student/StudentMapperTest.java
> feat: 수강생과정일련번호로 수강생 기본정보 찾기 메서드 요청사항 구현

- src/main/java/com/kosta/ems/attendance/AttendanceListBySearchFilterDTO.java
- src/main/java/com/kosta/ems/attendance/AttendanceMapper.java
- src/main/java/com/kosta/ems/attendance/RequestStudentAttendanceDTO.java
- src/main/resources/mapper/AttendanceMapper.xml
- src/test/java/com/kosta/ems/attendance/AttendanceMapperTest.java
feat: 특정일 수강생 출결상태 조회 mapper 작성, 테스트 완료
> feat: 특정일 수강생 출결상태 조회 mapper 작성, 테스트 완료

- src/main/java/com/kosta/ems/attendance/AttendanceService.java
- src/main/java/com/kosta/ems/attendance/AttendanceServiceImpl.java
- src/main/resources/mapper/AttendanceMapper.xml
- src/test/java/com/kosta/ems/attendance/AttendanceMapperTest.java
- src/test/java/com/kosta/ems/attendance/AttendanceServiceImplTest.java
* 특정일 수강생 출결상태 조회 service 작성, 테스트
* 특정일 수강생 출결상태 조회 mapper 일부 수정
* 경우2, 경우3에 대하여 select에 student_course_seq 누락 파악하여 추가
* 매개변수 데이터타입 변경사항 적용
> feat: 특정일 수강생 출결상태 조회 service 작성, 테스트 완료

- src/main/resources/templates/courses/courseBoard.html
> hotfix: baseUrl 변경에 따른 수정사항 적용

- src/main/java/com/kosta/ems/attendance/AttendanceController.java
- src/main/java/com/kosta/ems/attendance/AttendanceMapper.java
- src/main/java/com/kosta/ems/attendance/AttendanceServiceImpl.java
- src/main/resources/mapper/AttendanceMapper.xml
- src/main/resources/templates/students/attendanceBoard.html
- src/test/java/com/kosta/ems/attendance/AttendanceMapperTest.java
feat: 출결_출결 상태 검색 목록 controller 구현 및 해당 부분 js 일부 작성
> feat: 출결_출결 상태 검색 목록 controller 구현 및 해당 부분 js 일부 작성

- src/main/java/com/kosta/ems/EmpController.java
- src/main/java/com/kosta/ems/studentPoint/StudentPointMapper.java
- src/main/java/com/kosta/ems/studentPoint/StudentPointService.java
- src/main/java/com/kosta/ems/studentPoint/StudentPointServiceImpl.java
- src/main/resources/mapper/StudentPointMapper.xml
- src/main/resources/static/css/scholarships.css
- src/main/resources/templates/students/addPointModal.html
- src/main/resources/templates/students/pointBoard.html
- src/test/java/com/kosta/ems/studentPoint/StudentPointMapperTest.java
- src/test/java/com/kosta/ems/studentPoint/StudentPointServiceTest.java
==== Completed Source Code ====
pointBoard.html
StudentPointController
StudentPointService
StudentPointMapper
studentPoint.xml
> feat: Points FE&BE complete

- src/main/java/com/kosta/ems/attendance/AttendanceController.java
- src/main/java/com/kosta/ems/attendance/AttendanceMapper.java
- src/main/java/com/kosta/ems/attendance/AttendanceService.java
- src/main/java/com/kosta/ems/attendance/AttendanceServiceImpl.java
- src/main/resources/mapper/AttendanceMapper.xml
- src/main/resources/static/css/format.css
- src/main/resources/static/css/students.css
- src/main/resources/templates/common/headerDropdown.html
- src/main/resources/templates/students/attendanceBoard.html
- src/test/java/com/kosta/ems/attendance/AttendanceServiceImplTest.java
완료 사항
* common 헤더 드롭다운 출결 조회 항목 추가
* common 헤더 드롭다운 그림자 구분선 추가
* student.css 검색 버튼 스타일 수정
> style: 드롭다운에 출결조회 항목 추가, students 검색 버튼 스타일 수정 등

- src/main/java/com/kosta/ems/EmpController.java
- src/main/java/com/kosta/ems/course/CourseController.java
- src/main/java/com/kosta/ems/course/CourseService.java
- src/main/java/com/kosta/ems/manager/ManagerController.java
- src/main/java/com/kosta/ems/manager/ManagerService.java
- src/main/java/com/kosta/ems/studentPoint/StudentPointController.java
- src/main/java/com/kosta/ems/studentPoint/StudentPointService.java
courseController: service -> courseService
managerController: service -> managerService
> hotfix: Controller 내부 service 변수명 명확하게 변경

- src/main/java/com/kosta/ems/attendance/AttendanceController.java
- src/main/java/com/kosta/ems/attendance/AttendanceServiceImpl.java
- src/main/java/com/kosta/ems/attendance/StudentAttendanceListDTO.java
- src/main/resources/mapper/AttendanceMapper.xml
- src/main/resources/templates/students/attendanceBoard.html
- src/test/java/com/kosta/ems/attendance/AttendanceMapperTest.java
- src/test/java/com/kosta/ems/attendance/AttendanceServiceImplTest.java
- 페이징 처리 LIMIT 연산에 대해 잘못 생각한 부분이 있어 수정
- UI 스타일링 적용 중
> feat: 출결조회 페이지 sql 수정 및 테스트, UI 적용

- pom.xml
> feat: security 추가

- src/main/java/com/kosta/ems/config/PlainEncoder.java
- src/main/java/com/kosta/ems/config/UserDetailService.java
- src/main/java/com/kosta/ems/config/WebSecurityConfig.java
- src/main/java/com/kosta/ems/manager/ManagerDTO.java
- src/main/java/com/kosta/ems/manager/ManagerMapper.java
- src/main/resources/mapper/ManagerMapper.xml
- src/main/resources/templates/login/login.html
- src/test/java/com/kosta/ems/manager/ManagerMapperTest.java
> feat: Apply Spring Boot Security

- src/test/java/com/kosta/ems/course/CourseMapperTest.java
- src/test/java/com/kosta/ems/notification/NotificationMapperTest.java
- src/test/java/com/kosta/ems/notification/NotificationServiceTest.java
> chore: Test code 수정

- src/main/java/com/kosta/ems/student/StudentController.java
- src/main/java/com/kosta/ems/student/StudentMapper.java
- src/main/java/com/kosta/ems/student/StudentServiceImpl.java
- src/main/resources/mapper/AttendanceMapper.xml
- src/main/resources/mapper/StudentMapper.xml
- src/main/resources/static/assets/navigate_next_white_24dp 1.svg
- src/main/resources/static/assets/navigate_prev_white_24dp 1.svg
- src/main/resources/static/css/reset.css
- src/main/resources/static/css/students.css
- src/main/resources/templates/students/studentBoard.html
* 피드백 사항
* 수강생 정보 페이지 초기화면에 전체 데이터 바로 보여주기
* 수강생 정보 페이지 노출 데이터 줄이고, 상세 정보 모달 작성
* 수강생 정보 페이지 노출 데이터(table column) 줄이기 완료
> style: table 통일성을 위한 스타일 작업 및 피드백 반영

- pom.xml
- src/main/java/com/kosta/ems/attendance/AttendanceAcknowledgeDTO.java
- src/main/java/com/kosta/ems/attendance/AttendanceController.java
- src/main/java/com/kosta/ems/attendance/AttendanceMapper.java
- src/main/java/com/kosta/ems/attendance/AttendanceService.java
- src/main/java/com/kosta/ems/attendance/AttendanceServiceImpl.java
- src/main/java/com/kosta/ems/attendance/RequestAcknowledgeDTO.java
- src/main/java/com/kosta/ems/attendance/RequestStudentAttendanceDTO.java
- src/main/java/com/kosta/ems/config/AWSConfig.java
- src/main/java/com/kosta/ems/student/PageRequestDTO.java
- src/main/java/com/kosta/ems/student/ResCode.java
- src/main/java/com/kosta/ems/student/StudentMapper.java
- src/main/java/com/kosta/ems/student/StudentService.java
- src/main/java/com/kosta/ems/student/StudentServiceImpl.java
- src/main/resources/mapper/AttendanceMapper.xml
- src/main/resources/mapper/StudentMapper.xml
- src/main/resources/static/css/attendances.css
- src/main/resources/static/css/students.css
- src/main/resources/templates/students/addAttendance.html
- src/main/resources/templates/students/addStudent.html
- src/main/resources/templates/students/attendanceBoard.html
- src/main/resources/templates/students/studentBoard.html
- src/test/java/com/kosta/ems/attendance/AttendanceMapperTest.java
- src/test/java/com/kosta/ems/attendance/AttendanceServiceImplTest.java
- src/test/java/com/kosta/ems/student/StudentMapperTest.java
- src/test/java/com/kosta/ems/student/StudentServiceTest.java
> feat: attendance 출석인정서류 업로드 service 작업 중

- src/main/resources/templates/students/addAttendance.html
출결 입력 페이지인데 수강생 등록 페이지 코드 작성된 내용 수정함
> chore: addAttendance html 파일 잘못 작성된 내용 복구

- src/main/resources/static/css/courses.css
- src/main/resources/static/css/scholarships.css
- src/main/resources/templates/students/pointBoard.html
> fix: FE 과정관리, 포인트조회 css 수정

- src/main/resources/static/css/main.css
- src/main/resources/static/css/notifications.css
- src/main/resources/templates/notifications/notification.html
- 공통 스타일링 적용 사항
- table 높이 조정
- 버튼 크기 조정
- 공지사항 페이지
- 수정페이지 input 정렬 맞춤
- 삭제 확인 모달 버튼 컬러 변경
> style: 메인, 공지사항 페이지 공통 스타일링 적용

- src/main/resources/static/css/courses.css
- src/main/resources/templates/courses/courseBoard.html
- 적용 내용
- 공통 스타일 적용
- table 높이 조정
- courseBoard페이지의 button 크기 조정 (모달 포함)
- section 기본 정렬 수정
- 페이지네이션 정렬
- 수정 버튼 크기 table에 맞춰 수정
> style: 과정관리 페이지 공통 스타일 적용

- src/main/java/com/kosta/ems/attendance/AttendanceController.java
- src/main/java/com/kosta/ems/student/StudentController.java
- src/main/resources/static/css/attendances.css
- src/main/resources/static/css/notifications.css
- src/main/resources/static/css/students.css
- src/main/resources/templates/students/addAttendance.html
- src/main/resources/templates/students/addStudent.html
- src/main/resources/templates/students/attendanceBoard.html
- src/main/resources/templates/students/studentBoard.html
- 적용 범위
- 수강생 정보 페이지
- 공지사항 페이지
- 출결 조회 페이지
- 출결 입력 페이지
> style: 공통 스타일 적용
